# Generate the _webrarian.yml key reference from config_spec()
#
# Writes two files from the key table in R/config-spec.R, so that neither can
# drift from what webrarian reads:
#
#   vignettes/config-reference.qmd   the "Configuration reference" article
#   inst/templates/_webrarian.yml    every key with its default, annotated
#
# Run it from the package root after changing config_spec():
#
#   Rscript tools/config-reference.R
#
# tests/testthat/test-docs-reference.R fails while either file is stale. The
# functions below take the tables as arguments, so the test can source this
# file and compare its output with the committed files.

reference_key <- function(key) gsub("_", "-", key, fixed = TRUE)

reference_type <- function(entry) {
  switch(
    entry$type,
    string = "text",
    string_or_null = "text or null",
    version = "quoted version",
    strings = "list of text",
    strings_or_null = "list of text, or null",
    flag = "`true` or `false`",
    choice = paste0("one of ", paste0("`\"", entry$values, "\"`", collapse = ", ")),
    brand = "path or mapping",
    entry$type
  )
}

reference_yaml_value <- function(value) {
  if (is.null(value)) {
    return("null")
  }
  if (is.logical(value) && length(value) == 1L) {
    return(if (isTRUE(value)) "true" else "false")
  }
  if (is.list(value) || length(value) != 1L) {
    items <- unlist(value, use.names = FALSE)
    if (length(items) == 0L) {
      return("[]")
    }
    return(paste0(
      "[",
      paste(vapply(items, reference_yaml_value, character(1)), collapse = ", "),
      "]"
    ))
  }
  if (is.character(value)) {
    return(encodeString(value, quote = "\""))
  }
  as.character(value)
}

reference_markdown <- function(text) {
  text <- gsub("\\", "\\\\", text, fixed = TRUE)
  for (ch in c("*", "_", "|", "<", "[", "]")) {
    text <- gsub(ch, paste0("\\", ch), text, fixed = TRUE)
  }
  text
}

# The annotated _webrarian.yml: every key, its description and its default.
reference_template_lines <- function(spec) {
  out <- c(
    "# _webrarian.yml: every setting webrarian reads, with its default.",
    "# Generated from config_spec() by tools/config-reference.R, and described in",
    "# vignette(\"config-reference\", package = \"webrarian\").",
    "# Keys are lowercase with hyphens. settings_set(), acquire_*() and",
    "# withdraw_*() rewrite the file, so comments in it are not kept."
  )
  previous <- character()
  for (entry in spec) {
    segments <- strsplit(reference_key(entry$key), ".", fixed = TRUE)[[1]]
    parents <- segments[-length(segments)]
    common <- 0L
    while (
      common < min(length(parents), length(previous)) &&
        identical(parents[[common + 1L]], previous[[common + 1L]])
    ) {
      common <- common + 1L
    }
    if (common == 0L) {
      out <- c(out, "")
    }
    for (i in seq_along(parents)) {
      if (i > common) {
        out <- c(out, paste0(strrep("  ", i - 1L), parents[[i]], ":"))
      }
    }
    indent <- strrep("  ", length(parents))
    out <- c(out, paste0(indent, "# ", strwrap(entry$doc, width = 76L - nchar(indent))))
    out <- c(
      out,
      paste0(indent, segments[[length(segments)]], ": ", reference_yaml_value(entry$default))
    )
    previous <- parents
  }
  out
}

# The "Configuration reference" article.
reference_article_lines <- function(spec) {
  groups <- vapply(spec, function(e) strsplit(e$key, ".", fixed = TRUE)[[1]][[1]], character(1))
  out <- c(
    "---",
    "title: \"Configuration reference\"",
    "vignette: >",
    "  %\\VignetteIndexEntry{Configuration reference}",
    "  %\\VignetteEngine{quarto::html}",
    "  %\\VignetteEncoding{UTF-8}",
    "---",
    "",
    "<!-- Generated by tools/config-reference.R from config_spec() in R/config-spec.R.",
    "     Edit those, then run: Rscript tools/config-reference.R -->",
    "",
    "Each collection keeps its settings in `_webrarian.yml`. This page lists every key",
    "webrarian reads. It is generated from the table webrarian itself uses to read the",
    "file, so the two cannot disagree. A dotted name such as `repl.share-links` means",
    "the `share-links` key inside the `repl` mapping.",
    "",
    "```yaml",
    "# _webrarian.yml",
    "repl:",
    "  share-links: \"fixed\"",
    "```",
    "",
    "## File rules",
    "",
    "These rules apply to the whole file.",
    "",
    "- Keys are lowercase with hyphens. A key written with an underscore",
    "  (`output_dir`) is an error that gives the hyphenated spelling.",
    "- An unknown key is ignored, with a warning that suggests the nearest real key",
    "  when the spelling is close.",
    "- A value of the wrong type is an error that names the key and the type it needs.",
    "- A key left out, or set to `null`, takes its default.",
    "- Keys under `brand` are not checked, because they follow Posit's",
    "  [brand.yml](https://posit-dev.github.io/brand-yml/) standard.",
    "- YAML reads an unquoted `yes`, `no`, `on` or `off` as true or false. For",
    "  `repl.share-links` alone webrarian reads that false back as `\"off\"`, so",
    "  `share-links: off` works with or without quotes. Quote other text values.",
    "- `settings_set()`, `acquire_package()`, `acquire_file()`, `withdraw_package()`",
    "  and `withdraw_file()` rewrite the whole file, so comments in it are not kept."
  )
  for (group in unique(groups)) {
    out <- c(
      out,
      "",
      paste0("## `", group, "`"),
      "",
      "| Key | Type | Default | What it does |",
      "|-----|------|---------|--------------|"
    )
    for (entry in spec[groups == group]) {
      default <- if (is.null(entry$default)) {
        "unset"
      } else {
        paste0("`", reference_yaml_value(entry$default), "`")
      }
      out <- c(
        out,
        sprintf(
          "| `%s` | %s | %s | %s |",
          reference_key(entry$key),
          reference_type(entry),
          default,
          reference_markdown(entry$doc)
        )
      )
    }
  }
  out <- c(
    out,
    "",
    "## Every key with its default",
    "",
    "Here are the same settings as one file. `bind()` reads it as it stands, and",
    "`system.file(\"templates\", \"_webrarian.yml\", package = \"webrarian\")` points to a copy.",
    "",
    "```yaml",
    reference_template_lines(spec),
    "```"
  )
  out
}

if (sys.nframe() == 0L) {
  pkgload::load_all(quiet = TRUE)
  spec <- config_spec()
  writeLines(
    reference_article_lines(spec),
    "vignettes/config-reference.qmd",
    useBytes = TRUE
  )
  writeLines(reference_template_lines(spec), "inst/templates/_webrarian.yml", useBytes = TRUE)
  cat("Wrote vignettes/config-reference.qmd and inst/templates/_webrarian.yml\n")
}
